package view;

public class VistaGeneral extends javax.swing.JFrame {

    /**
     * Creates new form vistaGeneral
     */
    public VistaGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presentacion = new javax.swing.JLabel();
        introducirSemilla = new javax.swing.JTextField();
        msgSeeL = new javax.swing.JLabel();
        cifrarBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        introducirMensaje = new javax.swing.JPasswordField();
        msgCifL = new javax.swing.JLabel();
        mensajeCifrado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        presentacion.setBackground(new java.awt.Color(0, 202, 204));
        presentacion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        presentacion.setForeground(new java.awt.Color(0, 102, 102));
        presentacion.setText("Cifrado");
        presentacion.setAutoscrolls(true);
        getContentPane().add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 29, 107, 54));

        introducirSemilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirSemillaActionPerformed(evt);
            }
        });
        getContentPane().add(introducirSemilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 164, 97, -1));

        msgSeeL.setText("Seed");
        getContentPane().add(msgSeeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 55, -1));

        cifrarBtn.setBackground(new java.awt.Color(0, 153, 153));
        cifrarBtn.setText("Cifrar!");
        getContentPane().add(cifrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 265, -1, -1));

        exitBtn.setText("salir");
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 265, 83, -1));
        getContentPane().add(introducirMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 164, 115, -1));

        msgCifL.setText("Mensaje");
        getContentPane().add(msgCifL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        mensajeCifrado.setEditable(false);
        mensajeCifrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mensajeCifradoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mensajeCifradoKeyTyped(evt);
            }
        });
        getContentPane().add(mensajeCifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 94, 337, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirSemillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirSemillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introducirSemillaActionPerformed

    private void mensajeCifradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensajeCifradoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mensajeCifradoKeyTyped

    private void mensajeCifradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensajeCifradoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mensajeCifradoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cifrarBtn;
    public javax.swing.JButton exitBtn;
    public javax.swing.JPasswordField introducirMensaje;
    public javax.swing.JTextField introducirSemilla;
    public javax.swing.JTextField mensajeCifrado;
    private javax.swing.JLabel msgCifL;
    private javax.swing.JLabel msgSeeL;
    private javax.swing.JLabel presentacion;
    // End of variables declaration//GEN-END:variables
}
